"use client";

import { useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { WordmarkParticles } from "@/components/marketing/kt/KtParticles";

/**
 * v2 redesign port of test-project's shared `<footer class="footer">`
 * (identical markup on all 7 static pages, generated by assets/build.sh's
 * `foot_of()`). Placeholder content from the prototype is replaced with the
 * real production details already used elsewhere in this app (contact page,
 * the pre-redesign footer) rather than carried over verbatim:
 *   - socials: the prototype's GH/in/X icons were all `href="#"`. This site
 *     only has real LinkedIn + Instagram accounts (see the footer this
 *     replaces), so those two are wired and the rest dropped rather than
 *     left as dead links.
 *   - studio address: the prototype marks this `<!-- PLACEHOLDER -->` in its
 *     source. Kanpur, Uttar Pradesh, India and the reply-time figure are the
 *     real values already stated on /contact.
 *   - "Open source" nav link (`href="#"` in the prototype) is dropped for
 *     the same reason.
 */

const companyLinks = [
  { href: "/", label: "Home" },
  { href: "/showcase", label: "Work" },
  { href: "/portfolio", label: "Portfolio" },
  { href: "/pricing", label: "Pricing" },
  { href: "/about", label: "About" },
  { href: "/services", label: "Services" },
  { href: "/contact", label: "Contact" },
  { href: "/careers", label: "Careers" },
  { href: "/verify", label: "Verify" },
];

const sectors = ["Logistics", "Fintech", "Legal tech", "Consumer", "Education", "Health", "Climate"];
const services = ["Web platforms", "Mobile apps", "AI systems", "Security research", "Design systems", "API architecture"];

export default function MarketingFooter() {
  const pathname = usePathname();
  const [seg, setSeg] = useState<"sectors" | "services">("sectors");
  const track = seg === "sectors" ? sectors : services;

  return (
    <footer className="kt-footer">
      <div className="kt-wrap">
        <div className="kt-foot-top">
          <div>
            <p className="kt-t-mono kt-foot-label">Socials</p>
            <div className="kt-socials">
              <a
                className="kt-social"
                href="https://www.linkedin.com/company/kaiketsutech/"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="LinkedIn"
              >
                in
              </a>
              <a
                className="kt-social"
                href="https://www.instagram.com/kaiketsutech/"
                target="_blank"
                rel="noopener noreferrer"
                aria-label="Instagram"
              >
                IG
              </a>
            </div>
          </div>
          <div>
            <p className="kt-t-mono kt-foot-label">Company</p>
            <div className="kt-foot-links">
              {companyLinks.map((l) => (
                <Link key={l.href} href={l.href} aria-current={pathname === l.href ? "page" : undefined}>
                  {l.label}
                </Link>
              ))}
              <a href="mailto:hello@kaiketsutech.online">Email us</a>
            </div>
          </div>
          <div>
            <p className="kt-t-mono kt-foot-label">Working with us</p>
            <p className="kt-t-small">
              Fixed scope, fixed price, and the code in your organisation from the first commit. Every enquiry gets a
              reply from an engineer, including the ones we turn down.
            </p>
          </div>
        </div>

        <div className="kt-seg" role="tablist" aria-label="Footer index">
          <button type="button" role="tab" aria-selected={seg === "sectors"} onClick={() => setSeg("sectors")}>
            Sectors
          </button>
          <button type="button" role="tab" aria-selected={seg === "services"} onClick={() => setSeg("services")}>
            Services
          </button>
        </div>
      </div>

      <div className="kt-foot-ghost kt-u-fade-x">
        <div className="kt-foot-ghost-track" aria-hidden="true">
          {[...track, ...track].map((s, i) => (
            <span key={i}>{s}</span>
          ))}
        </div>
      </div>

      <div className="kt-wrap">
        <div className="kt-foot-rule" aria-hidden="true" />

        <div className="kt-foot-contact">
          <div className="kt-foot-thumb" aria-hidden="true" style={{ overflow: "hidden" }}>
            <img src="/images/footer_left_image.jpg" alt="" style={{ width: "100%", height: "100%", objectFit: "cover", opacity: 0.8 }} />
          </div>
          <div>
            <div className="kt-foot-field">
              <p className="kt-t-mono">Studio</p>
              <p className="kt-val">
                Remote-first crew.
                <br />
                Kanpur, Uttar Pradesh, India.
              </p>
            </div>
            <div className="kt-foot-field">
              <p className="kt-t-mono">Phone</p>
              <p className="kt-val">
                <a href="tel:+917467831005">+91 74678 31005</a>
              </p>
            </div>
          </div>
          <div>
            <div className="kt-foot-field">
              <p className="kt-t-mono">Email</p>
              <p className="kt-val">
                <a href="mailto:hello@kaiketsutech.online">hello@kaiketsutech.online</a>
              </p>
              <Link className="kt-link-arrow" href="/contact">
                Start a project
              </Link>
            </div>
            <div className="kt-foot-field">
              <p className="kt-t-mono">Reply time</p>
              <p className="kt-val">Within two working days</p>
            </div>
          </div>
          <div className="kt-dotfield" aria-hidden="true" style={{ overflow: "hidden" }}>
            <img src="/images/footer_right_image.jpg" alt="" style={{ width: "100%", height: "100%", objectFit: "cover", opacity: 0.8 }} />
          </div>
        </div>

        <div className="kt-foot-legal">
          <p className="kt-t-mono">&copy; {new Date().getFullYear()} KaiketsuTech &mdash; a student-run studio</p>
          <div className="kt-foot-policies kt-t-mono">
            <a href="#">Privacy</a>
            <a href="#">Terms</a>
            <a href="#">Security</a>
            <a href="#">Accessibility</a>
          </div>
          <p className="kt-t-mono">Built monochrome. No gradient without a job.</p>
        </div>
      </div>

      <WordmarkParticles text="KAIKETSU_TECH" />
    </footer>
  );
}
