"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { createClient } from "@/lib/supabase/client";
import { KtNavButton } from "@/components/marketing/kt/KtButton";

/**
 * v2 redesign port — visual design, markup and behaviour ported from
 * test-project's shared `.sitebar` / `.menu` chrome (identical across all 7
 * static pages there, generated by assets/build.sh's `nav_of()`). Two
 * deliberate departures from the static prototype, both preserving existing
 * production behaviour rather than the source HTML:
 *
 *  1. Link set: the redesign's interior pages only ever link to
 *     work/services/pricing/about/careers (Contact is the CTA pill). This
 *     app also has real, indexed /verify and /contact destinations that
 *     predate the redesign — dropping them from the nav would make them
 *     harder to find, so they're kept as two extra links rather than folded
 *     away.
 *  2. The CTA: test-project's pill is an unconditional link to contact.html
 *     (the prototype has no auth). Production's "Start a project" is the
 *     front door to the auth-gated request-a-project flow — a signed-in
 *     visitor should see "Dashboard" and go straight back to their account,
 *     exactly as the pre-redesign nav did. That auth-aware logic (session
 *     lookup, role-based dashboard href) is carried over unchanged; only the
 *     button's visual shell (now KtNavButton / RadialRevealButton) and the
 *     surrounding markup changed.
 */

const links = [
  { href: "/showcase", label: "Work" },
  { href: "/services", label: "Services" },
  { href: "/pricing", label: "Pricing" },
  { href: "/about", label: "About" },
  { href: "/careers", label: "Careers" },
  { href: "/verify", label: "Verify" },
  { href: "/contact", label: "Contact" },
];

export default function MarketingNav() {
  const pathname = usePathname();
  const [open, setOpen] = useState(false);
  const [signedIn, setSignedIn] = useState(false);
  const [dashboardHref, setDashboardHref] = useState("/dashboard/client");

  useEffect(() => {
    const supabase = createClient();
    let active = true;

    const applySession = (userId: string | undefined, metaRole: string | undefined) => {
      if (!active) return;
      setSignedIn(!!userId);
      if (userId) {
        if (metaRole) {
          setDashboardHref(`/dashboard/${metaRole}`);
        } else {
          supabase
            .from("profiles")
            .select("role")
            .eq("id", userId)
            .single()
            .then(({ data }) => {
              if (active && data?.role) setDashboardHref(`/dashboard/${data.role}`);
            });
        }
      }
    };

    supabase.auth.getUser().then(({ data }) => {
      applySession(data.user?.id, data.user?.user_metadata?.role);
    });

    const {
      data: { subscription },
    } = supabase.auth.onAuthStateChange((_event, session) => {
      applySession(session?.user?.id, session?.user?.user_metadata?.role);
    });

    return () => {
      active = false;
      subscription.unsubscribe();
    };
  }, []);

  // Mirrors kt.js's `body.is-open{overflow:hidden}` — the one piece of this
  // component's behaviour that has to reach outside its own DOM subtree.
  useEffect(() => {
    document.body.classList.toggle("kt-is-open", open);
    return () => document.body.classList.remove("kt-is-open");
  }, [open]);

  const ctaHref = signedIn ? dashboardHref : "/login?redirect=/request-project";
  const ctaLabel = signedIn ? "Dashboard" : "Start a project";

  return (
    <div className={open ? "kt-is-open" : ""}>
      <header className="kt-sitebar">
        <div className="kt-sitebar-in">
          <Link className="kt-brand-mark" href="/" aria-label="KaiketsuTech home">
            KAIKETSU<span className="kt-accent">_</span>TECH
          </Link>
          <nav className="kt-navlinks" aria-label="Primary">
            {links.map((l) => (
              <Link key={l.href} href={l.href} aria-current={pathname === l.href ? "page" : undefined}>
                {l.label}
              </Link>
            ))}
          </nav>
          <div className="hidden md:block">
            <KtNavButton href={ctaHref} label={ctaLabel} theme="dark" />
          </div>
          <button
            className="kt-burger"
            id="kt-burger"
            aria-label={open ? "Close menu" : "Open menu"}
            aria-expanded={open}
            onClick={() => setOpen((v) => !v)}
          >
            <i />
            <i />
          </button>
        </div>
      </header>

      <nav className="kt-menu" aria-hidden={!open}>
        <div className="kt-menu-inner">
          <p className="kt-menu-eyebrow">Menu</p>
          <ul className="kt-menu-list">
            {links.map((l) => (
              <li key={l.href}>
                <Link href={l.href} onClick={() => setOpen(false)}>
                  {l.label}
                </Link>
              </li>
            ))}
          </ul>
          <div className="kt-menu-foot">
            <Link className="kt-pill" href={ctaHref} onClick={() => setOpen(false)}>
              {ctaLabel}
            </Link>
            <Link className="kt-ghost-menu" href="/" onClick={() => setOpen(false)}>
              Back to home
            </Link>
          </div>
        </div>
      </nav>
    </div>
  );
}
