import type { ReactNode } from "react";
import { KtReveal } from "./KtReveal";

/** Shared `.kt-pagehead` — identical structure on every interior marketing
 * page (about/careers/contact/pricing/services/showcase), generated by
 * test-project's assets/build.sh `pagehead_of()`. */
export function KtPageHead({ eyebrow, title, lede, imageSrc }: { eyebrow: string; title: ReactNode; lede?: ReactNode; imageSrc?: string }) {
  return (
    <section className="kt-pagehead">
      <div className="kt-pagehead-field" aria-hidden="true" style={imageSrc ? { opacity: 1 } : {}}>
        {imageSrc ? (
          <img src={imageSrc} alt="" style={{ width: "100%", height: "100%", objectFit: "cover", opacity: 0.35 }} />
        ) : (
          <div className="kt-u-halftone" style={{ width: "100%", height: "100%" }} />
        )}
      </div>
      <div className="kt-wrap kt-pagehead-in">
        <KtReveal as="p" className="kt-t-mono kt-eyebrow">
          {eyebrow}
        </KtReveal>
        <KtReveal as="h1" index={1} className="kt-t-h1">
          {title}
        </KtReveal>
        {lede && (
          <KtReveal as="p" index={2} className="kt-t-body kt-lede">
            {lede}
          </KtReveal>
        )}
      </div>
    </section>
  );
}
